# Generated by Django 5.1.3 on 2024-11-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('interactive', 'Interactive')], max_length=20)),
            ],
        ),
    ]
